# Default values for vms-on-ocpv
# This is a YAML-formatted file.

# Common metadata that will be applied to all resources
common:
  metadata:
    labels:
      environment: ztp-testing
      owner: v1k0d3n
      demo: ztp-kubevirt-redfish
      redfish-enabled: "true"
    annotations:
      description: "This cluster was created using the vms-on-ocpv Helm chart"

# Virtual Machine configuration
VirtualMachine:
  baseName: ztp-jinkit-kvm
  count: 3
  runStrategy: Halted
  architecture: amd64
  machineType: pc-q35-rhel9.6.0
  resources:
    cpuCount: 20
    memoryCount: 48Gi
    disks:
      - name: disk1
        diskSize: 120Gi
      - name: disk2
        diskSize: 100Gi
    storageClass: lvms-vg1-immediate
    network:
      networkName: default/vlan3
      baseMAC: "00:50:56:03:17"
